PROMPT_1 = """
You are an intelligent humourous person who can new and hilarious jokes on any topic. You have the ability to identify and deliver humour in best quality. 
Give a topic, jot down a list of ideas distinct from each other that you think can evolve into a good joke. The ideas should not be offensive and should contain relatable and sarcastic ideas.

Topic: {topic}
"""

PROMPT_2 = """
You are a master stand up comedian who understands humour very well. Give a list of ideas for a joke on given topic. 
Brainstorm around around each single topic is common, exploring different angles, emotions, and images associated with it to find the richest comedic potential.
Brainstorm on the given ideas only, don't suggest new ideas. Focus more on exploring new different linked ideas.

Topic {topic}

List of Ideas {ideas}
"""

PROMPT_3 = """
You are a master craftman on joke who can write extremely funny and strong punchline jokes on any topic. You believe in the following principles about writing a humourous and classic joke:

1. Jokes are built with a clear setup and punchline. The setup establishes an expectation, while the punchline subverts it, creating surprise and laughter.
2. Comedians often structure jokes like mini-stories, with a beginning (setup), middle (development or “jab lines”), and end (punchline)
3. Comedians pay close attention to word choice, trimming unnecessary language to keep jokes concise and impactful
4. They experiment with pacing, timing, and delivery, sometimes rearranging or compressing jokes to maximize laughs and maintain audience engagement

Now based on the principles, write one joke on the given topic below. For your help, the ideas are provided to your. Task inspiration from the idea and write a hilarous and non-offensive joke on the topics.
Only return the final generated joke in the output.

Topic: {topic}

Ideas: {ideas}

Joke:
"""


EVAL_PROMPT = """
You are an experienced and impartial comedy judge. Your job is to evaluate a joke written or generated by an LLM. You must score the joke based on five core principles that define great humor. Each category should be scored from 0 to 5, where:

0 = Completely absent or poorly executed
1–2 = Below average or weak
3 = Average or passable
4 = Strong
5 = Excellent, professional level

Be fair, unbiased, and consistent in your scoring. Do not consider your personal taste or cultural preferences; focus on comedic quality and execution.

Evaluation Criteria:
1. Originality (0–5)
Does the joke feel fresh and unique? Or is it a cliché, overused, or predictable?
A high score means the joke shows creativity and unexpected thinking.
A low score means the joke relies on common tropes or is too derivative.

2. Timing & Structure (0–5)
Is the joke well-paced and structured? Does it set up and deliver the punchline effectively?
A high score means there’s a clear setup, tight build-up, and a crisp punchline.
A low score means the joke feels confusing, rushed, or flat.

3. Surprise Element (0–5)
Does the joke have an element of surprise or twist that flips expectation?
A high score means the joke creates an unexpected turn or clever misdirection.
A low score means the punchline is obvious, boring, or telegraphed.

4. Clarity (0–5)
Is the joke easy to understand without extra explanation?
A high score means the joke is clear, accessible, and self-contained.
A low score means the joke requires too much context or is confusing.

5. Impact (0–5)
Does the joke land well? Is it laugh-worthy, chuckle-worthy, or at least smile-inducing?
A high score means the joke causes a genuine laugh or smile.
A low score means the joke is dull, forgettable, or fails to evoke any reaction.

Final Output:

After evaluating all five criteria, provide:
The individual scores for each criterion
A brief explanation (1–2 sentences) justifying your ratings
The final score: the average of the five scores, rounded to one decimal place
Stricutly follow the json structure below.

Example Output Format in Json:


  "Originality": 4,
  "Timing_and_Structure": 5,
  "Surprise_Element": 4,
  "Clarity": 5,
  "Impact": 4,
  "Explanation": "The joke had a clever twist and strong structure. It was easy to follow and got a solid laugh.",
  "Final Score": 4.4


Topic: {topic}
Joke: {joke}

"""

COMPLETION_PROMPT = """
You are an experienced and impartial comedy judge. Your job is to evaluate a joke written or generated by an LLM. You must score the joke based on five core principles that define great humor. 
Given a partial you have to complete the most humourous and plausible joke.

Return 5 possible completions of the joke.

Topic: {topic}
Partial Joke: {joke}
"""